#!/bin/bash

find images -type f -iname "*.jpg" -print0 | while IFS= read -r -d $'\0' line; do
	echo "Current: $line"
	sqlite3 -line server/imagevote.db3 "INSERT INTO images (url) VALUES ('$line');"    
done
